name: Sync GitHub Release to Gitee

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  GITEE_OWNER: ${{ vars.GITEE_OWNER }}
  GITEE_REPO: ${{ vars.GITEE_REPO }}
  GITEE_TARGET_COMMITISH: ${{ vars.GITEE_TARGET_COMMITISH }}

jobs:
  sync-release-to-gitee:
    runs-on: ubuntu-latest

    steps:
    - name: Get release info
      id: release
      run: |
        # Get latest release info
        # release_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/latest"
        release_url="${GITHUB_API_URL}/repos/Terracotta/releases/releases/latest"
        
        response=$(curl -sL \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "${release_url}")
        
        formatted_response=$(echo "$response" | jq '{
          tag_name: .tag_name,
          name: .name,
          body: .body,
          prerelease: .prerelease,
          assets: [.assets[] | {name: .name, url: .browser_download_url}],
          html_url: .html_url
        }')
        
        echo "result=$formatted_response" >> $GITHUB_OUTPUT
        
        echo "Release info:"
        echo "$formatted_response"
      shell: bash

    - name: Download all release assets
      run: |
        mkdir assets
        for url in $(jq -r '.assets[].url' <<< '${{ steps.release.outputs.result }}'); do
          fname=$(basename "$url")
          curl -L -o "assets/$fname" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$url"
        done
      shell: bash

    - name: Create Gitee Release
      id: gitee_release
      run: |
        # Combine original body with GitHub release URL
        body="${{ fromJson(steps.release.outputs.result).body }}
        GitHub Release: ${{ fromJson(steps.release.outputs.result).html_url }}"
        
        response=$(curl -s -X POST "https://gitee.com/api/v5/repos/${GITEE_OWNER}/${GITEE_REPO}/releases" \
          -d "access_token=${GITEE_TOKEN}" \
          -d "tag_name=${{ fromJson(steps.release.outputs.result).tag_name }}" \
          -d "name=${{ fromJson(steps.release.outputs.result).name }}" \
          -d "body=${body}" \
          -d "prerelease=${{ fromJson(steps.release.outputs.result).prerelease }}" \
          -d "target_commitish=${GITEE_TARGET_COMMITISH}")
        echo "$response"
        echo "id=$(echo $response | jq -r '.id')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Upload assets to Gitee Release
      run: |
        release_id=${{ steps.gitee_release.outputs.id }}
        for file in assets/*; do
          curl -X POST "https://gitee.com/api/v5/repos/${GITEE_OWNER}/${GITEE_REPO}/releases/${release_id}/attach_files" \
            -F "access_token=${GITEE_TOKEN}" \
            -F "file=@${file}"
        done
      shell: bash
