name: Sync GitHub Release to Gitee

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  GITEE_OWNER: ${{ vars.GITEE_OWNER }}
  GITEE_REPO: ${{ vars.GITEE_REPO }}
  GITEE_TARGET_COMMITISH: ${{ vars.GITEE_TARGET_COMMITISH }}

jobs:
  sync-release-to-gitee:
    runs-on: ubuntu-latest

    steps:
    - name: Get release info
      id: release
      run: |
        # Get latest release info
        release_url="${GITHUB_API_URL}/repos/burningtnt/Terracotta/releases/latest"
        
        response=$(wget -d --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header="Accept: application/vnd.github.v3+json" \
          -O- "${release_url}")
        
        formatted_response=$(echo "$response" | jq -c '{
          tag_name: .tag_name,
          name: .name,
          body: .body,
          prerelease: .prerelease,
          assets: [.assets[] | {name: .name, url: .browser_download_url}],
          html_url: .html_url
        }')
        
        echo "$formatted_response" > release_info.json
        
        echo "Release info:"
        echo "$formatted_response"
      shell: bash

    - name: Download all release assets
      run: |
        mkdir assets
        while IFS= read -r url; do
          fname=$(basename "$url")
          echo "Downloading $fname..."
          wget -d --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O "assets/$fname" "$url"
        done < <(jq -r '.assets[].url' release_info.json)
      shell: bash

    - name: Create Gitee Release
      id: gitee_release
      run: |
        release_info=$(cat release_info.json)
        tag_name=$(echo "$release_info" | jq -r '.tag_name')
        name=$(echo "$release_info" | jq -r '.name')
        body=$(echo "$release_info" | jq -r '.body')
        html_url=$(echo "$release_info" | jq -r '.html_url')
        prerelease=$(echo "$release_info" | jq -r '.prerelease')
        
        # Combine original body with GitHub release URL
        body="${body}
        GitHub Release: ${html_url}"
        
        response=$(wget -d --post-data="access_token=${GITEE_TOKEN}&tag_name=${tag_name}&name=${name}&body=${body}&prerelease=${prerelease}&target_commitish=${GITEE_TARGET_COMMITISH}" \
          -O- "https://gitee.com/api/v5/repos/${GITEE_OWNER}/${GITEE_REPO}/releases")
        echo "$response"
        
        echo "$response" | jq -r '.id' > release_id.txt
      shell: bash

    - name: Upload assets to Gitee Release
      run: |
        release_id=$(cat release_id.txt)
        for file in assets/*; do
          wget -d --post-file="$file" \
            --header="Content-Type: multipart/form-data" \
            --post-data="access_token=${GITEE_TOKEN}" \
            -O- "https://gitee.com/api/v5/repos/${GITEE_OWNER}/${GITEE_REPO}/releases/${release_id}/attach_files"
        done
      shell: bash
